name: Sync autopass-cloudflare-captcha/ to adamlui/chatgpt-apps/autopass-cloudflare-captcha/

on:
  push:
    branches: [ master, main ]
    paths:
      - 'autopass-cloudflare-captcha/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync autopass-cloudflare-captcha/ to adamlui/chatgpt-apps/autopass-cloudflare-captcha/
        run: rsync -avh --delete ${{ github.workspace }}/adamlui/userscripts/autopass-cloudflare-captcha/ ${{ github.workspace }}/adamlui/chatgpt-apps/autopass-cloudflare-captcha/

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@userscripts.co
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: 'autopass-cloudflare-captcha/*'
          repository: adamlui/chatgpt-apps