name: Sync chatgpt/autoclear-chatgpt-history/ to (adamlui/autoclear-chatgpt-history/greasemonkey/ && adamlui/chatgpt-addons/autoclear-chatgpt-history/greasemonkey/)

on:
  push:
    branches: [ master, main ]
    paths:
      - 'chatgpt/autoclear-chatgpt-history/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/autoclear-chatgpt-history
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/autoclear-chatgpt-history
          path: adamlui/autoclear-chatgpt-history

      - name: Checkout adamlui/chatgpt-addons
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-addons
          path: adamlui/chatgpt-addons

      - name: Copy README.md to adamlui/autoclear-chatgpt-history/ && adamlui/chatgpt-addons/autoclear-chatgpt-history
        run: xargs -n 1 cp -v -f ${{ github.workspace }}/adamlui/userscripts/chatgpt/autoclear-chatgpt-history/README.md<<<"${{ github.workspace }}/adamlui/autoclear-chatgpt-history/README.md ${{ github.workspace }}/adamlui/chatgpt-addons/autoclear-chatgpt-history/README.md"

      - name: Sync chatgpt/autoclear-chatgpt-history/ to adamlui/autoclear-chatgpt-history/greasemonkey/
        run: rsync -av --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/autoclear-chatgpt-history/ ${{ github.workspace }}/adamlui/autoclear-chatgpt-history/greasemonkey/

      - name: Sync chatgpt/autoclear-chatgpt-history/ to adamlui/chatgpt-addons/autoclear-chatgpt-history/greasemonkey/
        run: rsync -av --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/autoclear-chatgpt-history/ ${{ github.workspace }}/adamlui/chatgpt-addons/autoclear-chatgpt-history/greasemonkey/

      - name: Push to adamlui/autoclear-chatgpt-history
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@userscripts.co
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: '*'
          repository: adamlui/autoclear-chatgpt-history

      - name: Push to adamlui/chatgpt-addons
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@userscripts.co
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: 'autoclear-chatgpt-history/*'
          repository: adamlui/chatgpt-addons