name: Sync chatgpt/chatgpt-widescreen-mode to adamlui/chatgpt-widescreen/greasemonkey

on:
  push:
    branches: [ master, main ]
    paths:
      - 'chatgpt/chatgpt-widescreen-mode/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-widescreen
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-widescreen
          path: adamlui/chatgpt-widescreen

      - name: Sync adamlui/userscripts/chatgpt/chatgpt-widescreen-mode to adamlui/chatgpt-widescreen/greasemonkey
        run: rsync -av --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-widescreen-mode/ ${{ github.workspace }}/adamlui/chatgpt-widescreen/greasemonkey/

      - name: Copy README.md to adamlui/chatgpt-widescreen
        run: cp -f ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-widescreen-mode/README.md ${{ github.workspace }}/adamlui/chatgpt-widescreen/README.md

      - name: Push to adamlui/chatgpt-widescreen
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@userscripts.co
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: '*'
          repository: adamlui/chatgpt-widescreen