name: Sync chatgpt/bravegpt/ to (kudoai/bravegpt/greasemonkey/ && adamlui/chatgpt-addons/bravegpt/greasemonkey/)

on:
  push:
    branches: [ master, main ]
    paths:
      - 'chatgpt/bravegpt/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout kudoai/bravegpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: kudoai/bravegpt
          path: kudoai/bravegpt

      - name: Checkout adamlui/chatgpt-addons
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-addons
          path: adamlui/chatgpt-addons

      - name: Copy README.md to kudoai/bravegpt/ && adamlui/chatgpt-addons/bravegpt
        run: xargs -n 1 cp -v -f ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/README.md<<<"${{ github.workspace }}/kudoai/bravegpt/README.md ${{ github.workspace }}/adamlui/chatgpt-addons/bravegpt/README.md"

      - name: Sync chatgpt/bravegpt/ to kudoai/bravegpt/greasemonkey/
        run: rsync -avh --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/ ${{ github.workspace }}/kudoai/bravegpt/greasemonkey/

      - name: Sync chatgpt/bravegpt/ to adamlui/chatgpt-addons/bravegpt/greasemonkey/
        run: rsync -avh --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/ ${{ github.workspace }}/adamlui/chatgpt-addons/bravegpt/greasemonkey/

      - name: Push to kudoai/bravegpt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@userscripts.co
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: '*'
          repository: kudoai/bravegpt

      - name: Push to adamlui/chatgpt-addons
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@userscripts.co
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: 'bravegpt/*'
          repository: adamlui/chatgpt-addons