name: Sync chatgpt/duckduckgpt to kudoai/duckduckgpt/greasemonkey

on:
  push:
    branches:
      - master
    paths:
      - 'chatgpt/duckduckgpt/**'
    if: 'github.event.head_commit.committer.username != "auto-sync-bot"'

jobs:
  sync-duckduckgpt:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout kudoai/duckduckgpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: kudoai/duckduckgpt
          path: kudoai/duckduckgpt

      - name: adamlui/userscripts/chatgpt/duckduckgpt to adamlui/duckduckgpt/greasemonkey
        run: rsync -av --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/ ${{ github.workspace }}/kudoai/duckduckgpt/greasemonkey/
      
      - name: Push to kudoai/duckduckgpt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@userscripts.co
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: '*'
          repository: kudoai/duckduckgpt